# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bots < Formula
  desc "Bots - Session Persistence & Decision Tracking CLI"
  homepage "https://github.com/AlvaroRausell/bots"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.1.0/bots_0.1.0_darwin_amd64.tar.gz"
      sha256 "7d7423f6582751a999e6e057d2a24190c96b263764eedb5dfc32409d3dd6a7bc"

      define_method(:install) do
        bin.install "bots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.1.0/bots_0.1.0_darwin_arm64.tar.gz"
      sha256 "dd40e9dd0d051bb153f6de7195d11631a2bda24af3511fdf6bc6c252fd629271"

      define_method(:install) do
        bin.install "bots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.1.0/bots_0.1.0_linux_amd64.tar.gz"
      sha256 "ee44c098aa2ef8604fda96adedc937989ce8cdc46b2958bf7f80895d71e736e0"
      define_method(:install) do
        bin.install "bots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.1.0/bots_0.1.0_linux_arm64.tar.gz"
      sha256 "6f3f18399965b6aff7d01a2cb7b3fd096d612cb041412af9f8c0f6ef2f3af7ae"
      define_method(:install) do
        bin.install "bots"
      end
    end
  end

  test do
    system "#{bin}/bots", "help"
  end
end
