# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bots < Formula
  desc "Bots - Session Persistence & Decision Tracking CLI"
  homepage "https://github.com/AlvaroRausell/bots"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.0.1/bots_0.0.1_darwin_amd64.tar.gz"
      sha256 "638f42f08391e74750d19750e8d19d292d8f809d7e1910ec7f7feaf97231afd6"

      define_method(:install) do
        bin.install "bots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.0.1/bots_0.0.1_darwin_arm64.tar.gz"
      sha256 "e0fc370417be79c80421082d374467f8b64cea524202b2b490e594c4b3a306cd"

      define_method(:install) do
        bin.install "bots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.0.1/bots_0.0.1_linux_amd64.tar.gz"
      sha256 "61401e2058103a1d925b8ab7c0d18b31e2342e6d5deccc04830ff5562c6e486d"
      define_method(:install) do
        bin.install "bots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlvaroRausell/bots/releases/download/v0.0.1/bots_0.0.1_linux_arm64.tar.gz"
      sha256 "bde7af6c979c34319342e1c339682089ebac253104627c153bb7f00f37090aec"
      define_method(:install) do
        bin.install "bots"
      end
    end
  end

  test do
    system "#{bin}/bots", "help"
  end
end
